//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjetBobines.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DimProduit
    {
        public int IdProduit { get; set; }
        public string Produit { get; set; }
        public string Type_Produit_ID { get; set; }
        public string Etat { get; set; }
        public Nullable<double> Largeur { get; set; }
        public Nullable<double> Longueur { get; set; }
        public Nullable<System.DateTime> Date_Creation { get; set; }
    }
}
