//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjetBobines.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Produit
    {
        public string D_NUM_PRODUIT { get; set; }
        public string Type_Produit_ID { get; set; }
        public string Etat { get; set; }
        public Nullable<int> Poids { get; set; }
        public Nullable<int> Largeur { get; set; }
        public Nullable<int> Longueur { get; set; }
        public Nullable<int> Epaisseur { get; set; }
        public Nullable<int> Diametre_Interieur { get; set; }
        public Nullable<int> Diametre_Exterieur { get; set; }
        public string Flux_ID { get; set; }
        public Nullable<System.DateTime> Date_Creation { get; set; }
        public Nullable<System.DateTime> Date_Reception { get; set; }
        public Nullable<System.DateTime> Date_Localisation { get; set; }
        public Nullable<System.DateTime> Date_FinVie { get; set; }
        public Nullable<int> X_Pont { get; set; }
        public Nullable<int> Y_Pont { get; set; }
        public Nullable<int> Z_Pont { get; set; }
        public Nullable<int> X_Calcule { get; set; }
        public Nullable<int> Y_Calcule { get; set; }
        public Nullable<int> Z_Calcule { get; set; }
        public string Hall_ID { get; set; }
        public string ZL_ID { get; set; }
        public string ZS_ID { get; set; }
        public Nullable<int> Emplacement_ID { get; set; }
        public Nullable<int> Rang { get; set; }
        public string CM_ID { get; set; }
        public Nullable<int> Berce_ID { get; set; }
        public Nullable<int> Emplacement_ID_CM { get; set; }
        public string Localisation_Utilisateur { get; set; }
        public string Securite_Violee { get; set; }
        public string Commentaire_Localisation { get; set; }
        public string Qui_A_Localise { get; set; }
        public Nullable<int> Lot_MK { get; set; }
        public Nullable<int> Poste_Commande { get; set; }
        public string Stade_Elaboration { get; set; }
        public Nullable<System.DateTime> Date_Coil_Froid { get; set; }
        public string Etat_UM { get; set; }
        public Nullable<int> Dernier_Code_Decision { get; set; }
        public string Code_Defaut_Principal { get; set; }
        public Nullable<int> Numero_Montage { get; set; }
        public Nullable<int> Numero_Montage_Previsionnel { get; set; }
        public Nullable<System.DateTime> Date_Pass_Prev_Out_Suiv { get; set; }
        public Nullable<int> Code_Client_Destinataire_Livra { get; set; }
        public string Client_Destinataire_Livraison { get; set; }
        public Nullable<int> Code_Client_Destinataire_Techn { get; set; }
        public string Client_Destinataire_Technique { get; set; }
        public Nullable<int> Code_Client_Utilisateur { get; set; }
        public string Client_Utilisateur { get; set; }
        public string Halle_Montataire { get; set; }
        public string Top_Emballage { get; set; }
        public string Qualite_Metal { get; set; }
        public Nullable<System.DateTime> Date_Entree_Magasin { get; set; }
        public Nullable<System.DateTime> Date_Sortie_Magasin { get; set; }
        public Nullable<System.DateTime> Date_Remise_Fabrication { get; set; }
        public Nullable<System.DateTime> Date_Chargement { get; set; }
        public Nullable<System.DateTime> Date_Expedition { get; set; }
        public Nullable<System.DateTime> Date_Inventaire { get; set; }
        public Nullable<System.DateTime> Delai_Expedition_Previsionnel { get; set; }
        public Nullable<int> Numero_Instruction { get; set; }
        public string Type_Instruction { get; set; }
        public Nullable<System.DateTime> Date_Chargement_Plus_Tot { get; set; }
        public Nullable<System.DateTime> Date_Chargement_Plus_Tard { get; set; }
        public Nullable<System.DateTime> Date_Livraison_Imperative { get; set; }
        public string Urgence_Instruction { get; set; }
        public Nullable<System.DateTime> Date_Urgence_Rouge { get; set; }
        public string Famille_Emballage { get; set; }
        public string Code_Emballage { get; set; }
        public string Code_Prestataire { get; set; }
        public string Mode_Expedition { get; set; }
        public string Nuance_Acier { get; set; }
        public Nullable<int> Diametre_Exterieur_Theorique { get; set; }
        public Nullable<int> Poids_Theorique { get; set; }
        public string Ticket_Bascule { get; set; }
        public Nullable<int> Longueur_Paquet { get; set; }
        public Nullable<int> Nombre_Feuille_Barre { get; set; }
        public string Indicateur_HR_THR { get; set; }
        public string Outil_Precedent { get; set; }
        public string Outil_Suivant { get; set; }
        public string Halle_ID_Destination { get; set; }
        public string Urgence_Transport_CID_GPO { get; set; }
        public string Halle_OG { get; set; }
        public string Localisation_OG { get; set; }
        public string Gerbabilite_Matiere { get; set; }
        public string Indicateur_Expediabilite { get; set; }
        public string UM_Huilee { get; set; }
        public string Outil_Suivant_nplus1 { get; set; }
        public string Urgence_Expedition { get; set; }
        public Nullable<int> CodeProduit { get; set; }
        public string Motif_Securite_Violee { get; set; }
        public string DemandeDeDelestage { get; set; }
        public string Localisation_Pour_OG { get; set; }
        public Nullable<System.DateTime> Date_Passage_Outil_Suivant { get; set; }
        public Nullable<int> Hauteur { get; set; }
        public string Gerbabilite_Autorisee { get; set; }
        public Nullable<int> X_Min_Occupation_Produit { get; set; }
        public Nullable<int> X_Max_Occupation_Produit { get; set; }
        public Nullable<int> Y_Min_Occupation_Produit { get; set; }
        public Nullable<int> Y_Max_Occupation_Produit { get; set; }
        public Nullable<int> X_Min_Zone_Securite { get; set; }
        public Nullable<int> X_Max_Zone_Securite { get; set; }
        public Nullable<int> Y_Min_Zone_Securite { get; set; }
        public Nullable<int> Y_Max_Zone_Securite { get; set; }
        public Nullable<int> X_Min_Zone_Accessibilite { get; set; }
        public Nullable<int> X_Max_Zone_Accessibilite { get; set; }
        public Nullable<int> Y_Min_Zone_Accessibilite { get; set; }
        public Nullable<int> Y_Max_Zone_Accessibilite { get; set; }
        public string Urgence_Local_Flux { get; set; }
        public string Hall_ID_Flux_Majeur { get; set; }
        public string Hall_ID_Flux_Mineur { get; set; }
        public string ZL_ID_Flux_Majeur { get; set; }
        public string ZL_ID_Flux_Mineur { get; set; }
        public Nullable<System.DateTime> Date_Execution_Demandee_Flux { get; set; }
        public string Hall_ID_Delestage { get; set; }
        public Nullable<System.DateTime> Date_Execution_Demandee_Delest { get; set; }
        public string Hall_ID_Rapprochement { get; set; }
        public Nullable<System.DateTime> Date_Execution_Demandee_Rappro { get; set; }
        public string TGV { get; set; }
        public string Emballage_Direct { get; set; }
        public Nullable<int> Poids_Bascule { get; set; }
        public Nullable<System.DateTime> DH_Derniere_Reception_Fiche { get; set; }
        public string Anomalie_OG { get; set; }
        public Nullable<System.DateTime> DH_Inventaire { get; set; }
        public string LigneMontataire { get; set; }
        public Nullable<System.DateTime> DH_Produit_Froid { get; set; }
        public string Type_Produit_Final { get; set; }
        public string Origine_Exterieure { get; set; }
        public Nullable<System.DateTime> DH_Donnees_OG { get; set; }
        public Nullable<System.DateTime> DH_Reception_Emission_Amont { get; set; }
        public Nullable<System.DateTime> DH_Reception_Emission_Aval { get; set; }
        public Nullable<int> Nombre_Fiche_Identique { get; set; }
        public string Parc { get; set; }
        public string Urgence_Antares { get; set; }
        public string Indicateur_Emballabilite { get; set; }
        public string Indicateur_Itochu { get; set; }
        public Nullable<System.DateTime> DH_Prev_Ent_Mag { get; set; }
        public string Indicateur_Cmd_Essai { get; set; }
        public string Indicateur_Def_Manu_DH_Prev_En { get; set; }
        public string Auteur_Def_Manu_DH_Prev_Ent_Ma { get; set; }
        public string Indicateur_Produit_Emballe { get; set; }
        public string Auteur_Dmd_Urgence_Flux { get; set; }
        public string Forcage_Emission_Fiche { get; set; }
        public string Demande_Rep_Deballage { get; set; }
        public string Type_Rep_Deballage { get; set; }
        public string Axe { get; set; }
        public Nullable<int> Choix { get; set; }
        public string LOK { get; set; }
        public string Nom_Principal_Colis { get; set; }
        public string UM { get; set; }
        public string Axe_Client { get; set; }
        public string Indicateur_Non_Derive { get; set; }
        public string Dernier_Outil { get; set; }
        public Nullable<System.DateTime> DH_Sortie_Dernier_Outil { get; set; }
        public string Indicateur_Reetiquetage { get; set; }
        public Nullable<System.DateTime> DH_Dmd_Reetiquetage { get; set; }
        public string AuteurUrgenceFlux { get; set; }
        public Nullable<System.DateTime> DHUrgenceFlux { get; set; }
        public string ZL_IdDestinationHalleMajeur { get; set; }
        public Nullable<System.DateTime> Date_Pass_Prev_Out_Suiv_OG { get; set; }
        public string Indicateur_Def_Manu_Date_Passa { get; set; }
        public string Auteur_Def_Manu_Date_Passage_P { get; set; }
        public string NumPlan { get; set; }
    }
}
